import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  // TODO change any type
  const [apiRes, setApiRes] = useState<ResponseTypeTODO>();

  useEffect(() => {
    fetch("/api/activities")
      .then((res) => res.json())
      .then((res) => setApiRes(res));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Planning App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {apiRes && <pre>{JSON.stringify(apiRes, undefined, 2)}</pre>}
      </main>
    </div>
  );
};

export default Home;
